### ISSUE TITLE
Likely scam page on esp-rs.org

### ISSUE THREAD

**Issue by m-vz** [esp-rs/esp-rs.github.io#2]
When dropping the hostname from https://docs.esp-rs.org I end up at a broken shopify (scam) page that looks like it might have been created by a bot with some picked up credentials... Probably worth looking into.

**Comment by jessebraham** [comment]
Thank you very much for reporting this. It is apparently a known issue that GitHub has yet to resolve, I was able to find other people complaining about the same thing happening to them (one such instance [here](https://rmoff.net/2024/01/16/hosting-on-github-pages-watch-out-for-subdomain-hijacking/)).

I've nuked our DNS records setting up the apex domain with GitHub, and left only the CNAME entry redirecting to our self-hosted documentation for now, so that spam site is no longer accessible via our domain. Hopefully we can figure out how to configure the apex domain in a secure manner in the future.
